print('Имя пользователя:', username)
print('заголовок заметки:', title)
print('описание заметки:', content)
print('статус заметки:', status)
print('дата создания заметки:', created_date)
print('дата истечения заметки:', issue_date)